#!/usr/bin/env bash
# Regenerate data/community-brands.js from the live curated list at
# api.knockoff.shopping, so fresh installs filter correctly before their
# first daily refresh. The /release skill runs this at release time.
set -euo pipefail
cd "$(dirname "$0")/.."

curl -sfL "https://api.knockoff.shopping/brands" -o /tmp/knockoff-brands.txt

python3 - <<'EOF'
import json

with open("/tmp/knockoff-brands.txt") as f:
    brands = [line.strip() for line in f if line.strip()]

# Refuse to bake a truncated or error response into a release.
if len(brands) < 1000:
    raise SystemExit("suspiciously short list (%d brands); refusing to write" % len(brands))

with open("data/community-brands.js") as f:
    old = f.read()

with open("data/community-brands.js", "w") as f:
    f.write("// Knockoff — bundled snapshot of the curated community allowlist (%d brands).\n" % len(brands))
    f.write("// Generated by scripts/update-bundled-brands.sh — do not edit by hand.\n")
    f.write("// Originally seeded from https://github.com/chris-mosley/AmazonBrandFilterList\n")
    f.write("// (MIT License, Copyright (c) 2023 Chris Mosley).\n")
    f.write("var KO_COMMUNITY_BRANDS = " + json.dumps(brands, ensure_ascii=False).replace("\n", "") + ";\n")

with open("data/community-brands.js") as f:
    changed = f.read() != old
print("%d brands written to data/community-brands.js%s" % (len(brands), "" if changed else " (unchanged)"))
EOF
